# This is a fully-commented example workflow showing how to use the PR Agent
# -------------------------------------------------------------------------
# Copy this file to .github/workflows/pr-agent.yml in any repository where
# you want the assistant to operate. Adjust inputs / secrets as needed.

name: "PR Agent"

# Trigger when someone comments `@agent` on a Pull Request *or* when a PR is
# opened/updated so the assistant can proactively review.
# Feel free to narrow / extend events to suit your workflow.
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    # Use the standard GitHub runner; Bun & Node are already present.
    runs-on: ubuntu-latest

    # Only run when the trigger phrase is present **or** on PR open/sync
    # (GitHub expressions let us reference the event body safely).
    if: |
      github.event_name == 'pull_request' ||
      contains(github.event.comment.body, '@agent')

    steps:
      # 1. Checkout the repository so PR files are available
      - uses: actions/checkout@v4

      # 2. Set up Bun (fast TS runtime). We pin to a version for consistency.
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.2'

      # 3. Invoke the composite Action **from this repo**. In real usage you’d
      #    reference a tagged release, e.g. `your-org/pr-agent@v1`.
      - name: Run PR Agent
        uses: ./pr-agent   # path to the action directory in this repo
        with:
          # Choose the model to use. Prefix determines provider:
          #   claude-* -> Anthropic, gpt-* / o3-* -> OpenAI
          model: ${{ env.OPENAI_MODEL }}

          # Optional: override trigger phrase (default is "@agent")
          trigger_phrase: "@agent"

          # Optional: maximum tokens allowed in prompt before diff is truncated
          max_tokens: 25000

          # Optional: LLM request timeout (ms)
          timeout_ms: 60000
        env:
          # Pass the API keys via GitHub repository secrets
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # These envs provide default models if `model:` input omitted
          OPENAI_MODEL: "o3-pro-2025-06-10"
          ANTHROPIC_MODEL: "claude-sonnet-4-20250514"

# -------------------------------------------------------------------------
# Usage tips:
# • Comment `@agent please review` on any PR to trigger.
# • Tune `trigger_phrase` if you want a different keyword.
# • Remove the `pull_request` event if you *only* want opt-in reviews.
# ------------------------------------------------------------------------- 